version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxxxxxxxxx
      MYSQL_DATABASE: bioserver
      MYSQL_USER: bioserver
      MYSQL_PASSWORD: 'xxxxxxxxxxxxxxxx'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
